/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import { GroupProps } from "@react-three/fiber";

const Globe = (props: GroupProps) => {
  const { nodes, materials } = useGLTF("models/globe/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.meshNode_Material_u1_v1_0 as THREE.Mesh).geometry}
            material={materials.Material_u1_v1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.meshNode_Material_u2_v1_0 as THREE.Mesh).geometry}
            material={materials.Material_u2_v1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.meshNode_Material_u1_v2_0 as THREE.Mesh).geometry}
            material={materials.Material_u1_v2}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("models/globe/scene.gltf");

export default Globe;
