import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LanguageProvider from "@/components/providers/LanguageProvider/LanguageProvider";
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Get the default language from headers or default to 'en'
  const headersList = headers();
  const acceptLanguage = headersList.get("accept-language");
  const defaultLang = acceptLanguage?.split(",")[0].split("-")[0] || "en";
  return (
    <html lang={defaultLang} data-theme="light">
      <body className={inter.className}>
        <LanguageProvider>{children}</LanguageProvider>
      </body>
    </html>
  );
}
